[package]
name = "pmem_hashmap"
version = "0.1.0"
build="build.rs"
edition = "2021"

[build-dependencies]
bindgen = "0.65"

[dependencies]
errno = "0.3.1"
thiserror = "1.0.40"
twox-hash = "1.6.3"

[dev-dependencies]
tempfile = "3.5.0"
